https://numpy.org/doc/stable/reference/generated/numpy.tensordot.html

In [1]:
import numpy as np

In [10]:
a = np.arange(50).reshape(5,10)
b = np.arange(40).reshape(10,4)
c = np.tensordot(a,b, axes=1)     # a기준 축1 ==>> (5,10)*(10,4)

print(c.shape)
print(c)

(5, 4)
[[1140 1185 1230 1275]
 [2940 3085 3230 3375]
 [4740 4985 5230 5475]
 [6540 6885 7230 7575]
 [8340 8785 9230 9675]]


In [14]:
a = np.arange(50).reshape(5,10)
b = np.arange(40).reshape(10,4)
c = np.tensordot(a,b, axes=0)     # a기준 축0 ==>> (5,10)*(10,4)

print(c.shape)

(5, 10, 10, 4)


In [15]:
a = np.arange(50).reshape(5,10)
b = np.arange(40).reshape(10,4)
c = np.tensordot(b,a, axes=0)     # b기준 축0 ==>> (10,4)*(5,10)

print(c.shape)

(10, 4, 5, 10)
